apiVersion: 1

datasources:
  - name: Wazuh-OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: https://wazuh-indexer:9200
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: ${WAZUH_INDEXER_PASSWORD}
    jsonData:
      database: wazuh-alerts-*
      timeField: timestamp
      esVersion: "7.10.0"
      tlsSkipVerify: true
      logMessageField: rule.description
      logLevelField: rule.level
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
